name: create tag/release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      -   name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

      -   name: Set Release version
          run: |
            mvn versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      -   name: Get pom version
          id: get_version
          run: |
            echo ::set-output name=VERSION::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Build with Maven
        run: mvn -B clean verify

      -   uses: rickstaa/action-create-tag@v1
          id: "tag_create"
          with:
            tag: ${{ steps.get_version.outputs.VERSION }}

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: target/*.jar

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      -   name: Checkout artifact
          uses: actions/download-artifact@v4
          with:
            name: jar
            path: target

      -   name: Create GitHub Release
          id: create_release
          uses: softprops/action-gh-release@v2
          with:
            draft: false
            prerelease: false
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: v${{ needs.build.outputs.version }}
            name: Release v${{ needs.build.outputs.version }}
            files: |
              ./target/keycloak-verify-email-by-code-${{ needs.build.outputs.version }}-javadoc.jar
              ./target/keycloak-verify-email-by-code-${{ needs.build.outputs.version }}-sources.jar
              ./target/keycloak-verify-email-by-code-${{ needs.build.outputs.version }}.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
